CREATE DATABASE clinic_db;

CREATE TABLE doctor
(
    id             int generated by default as identity primary key,
    name           varchar not null,
    specialization varchar not null
);

CREATE TABLE patient
(
    id   int generated by default as identity primary key,
    name varchar               not null,
    age  int check ( age > 0 ) not null,
    sex  varchar               not null,
    doctor_id int,
    foreign key (doctor_id) references doctor(id)
);
CREATE TABLE drug
(
    id    int generated by default as identity primary key,
    title varchar not null
);
create table patient_drug
(
    patient_id bigint not null,
    drug_id    bigint not null,
    primary key (patient_id, drug_id),
    constraint fk_patient_id foreign key (patient_id) references patient (id),
    constraint fk_drug_id foreign key (drug_id) references drug (id)
);



INSERT INTO doctor (name, specialization)
VALUES ('Mikhail', 'dentist');
INSERT INTO doctor (name, specialization)
VALUES ('Vladimir', 'surgeon');
INSERT INTO doctor (name, specialization)
VALUES ('Aleksei', 'psychologist');

INSERT INTO patient(name, age, sex, doctor_id)
VALUES ('Sergei', 22, 'male', 1);
INSERT INTO patient(name, age, sex, doctor_id)
VALUES ('Anna', 44, 'female', 1);
INSERT INTO patient(name, age, sex, doctor_id)
VALUES ('Anton', 50, 'male', 3);

INSERT INTO drug (title)
VALUES ('painkillers');
INSERT INTO drug (title)
VALUES ('sleeping pills');
INSERT INTO drug (title)
VALUES ('antibiotics');

INSERT INTO patient_drug (patient_id, drug_id)
VALUES (1, 3);
INSERT INTO patient_drug (patient_id, drug_id)
VALUES (1, 2);
INSERT INTO patient_drug (patient_id, drug_id)
VALUES (2, 1);
INSERT INTO patient_drug (patient_id, drug_id)
VALUES (3, 1);
INSERT INTO patient_drug (patient_id, drug_id)
VALUES (3, 2);
INSERT INTO patient_drug (patient_id, drug_id)
VALUES (3, 3);